format_version: 10
pipelines:
  build:
    group: defaultGroup
    materials:
      repo:
        type: configrepo
    stages:
      - build:
          clean_workspace: true
          artifacts:
            - build:
                source: build/libs
                destination: build
          tasks:
            - exec:
                command: ./gradlew
                arguments:
                  - build

