format_version: 10
pipelines:
  build:
    group: defaultGroup
    materials:
      repo:
        type: configrepo
    stages:
      - build:
          clean_workspace: true
          artifacts:
            - build:
                source: build/libs
                destination: build
          tasks:
            - exec:
                command: ./gradlew
                arguments:
                  - build
  docker:
    group: defaultGroup
    parameters:
      docker_registry: "localhost:5000"
    materials:
      repo:
        type: configrepo
      built_jar:
        pipeline: build
        stage: build
    stages:
      - build:
          clean_workspace: true
          tasks:
            - fetch:
                pipeline: build
                stage: build
                job: build
                source: build
                destination: .
            - exec:
                command: docker
                arguments:
                  - build
                  - "--tag"
                  - "#{docker_registry}/build-pipeline-demo"
                  - .
      - push:
          tasks:
            - exec:
                command: docker
                arguments:
                  - push
                  - "#{docker_registry}/build-pipeline-demo"

